MOVIES = {   '0012236131472': {   'directors': ['Quentin Tarantino'],
                         'genres': [   'Crime',
                                       'Gangsters',
                                       'DTS',
                                       'DVD',
                                       'Full Screen'],
                         'rating': 'R',
                         'stars': [   'Kirk Baltz',
                                      'Lawrence Bender',
                                      'Randy Brooks',
                                      'Edward Bunker',
                                      'Steve Buscemi'],
                         'title': 'Reservoir Dogs',
                         'year': 1992},
    '0043396189713': {   'directors': ['Andy Ackerman'],
                         'genres': [   'Domestic Comedies',
                                       'Seinfeld',
                                       'DTS',
                                       'Comedy',
                                       'Television',
                                       'DVD',
                                       'Boxed Set',
                                       'Full Screen'],
                         'rating': 'NR',
                         'stars': [],
                         'title': 'Seinfeld - Season 8',
                         'year': 2007},
    '0053939258325': {   'directors': ['Frank Darabont'],
                         'genres': [   'Buddies',
                                       'Redemption',
                                       'Miscarriage of Justice',
                                       'Prison Films',
                                       'DTS',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Tim Robbins',
                                      'Morgan Freeman',
                                      'Bob Gunton',
                                      'William Sadler',
                                      'Clancy Brown'],
                         'title': 'The Shawshank Redemption',
                         'year': 1994},
    '0717951009944': {   'directors': ['Stephen Frears'],
                         'genres': [   'Friends',
                                       'Contemporary',
                                       'John Cusack',
                                       'Rock',
                                       'DTS',
                                       'Zeta Jones, Catherine',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Lisa Bonet',
                                      'Joan Cusack',
                                      'John Cusack',
                                      'Sara Gilbert',
                                      'Catherine Zeta-Jones'],
                         'title': 'High Fidelity',
                         'year': 2000},
    '9780767802512': {   'directors': ['Luc Besson'],
                         'genres': [   'Thrillers',
                                       'Blackmail, Murder & Mayhem',
                                       'Action & Adventure',
                                       'Drama',
                                       'Buddy Films',
                                       'Coming of Age',
                                       'DTS',
                                       'France',
                                       'Mystery & Suspense',
                                       'DVD',
                                       'Full Screen'],
                         'rating': 'R',
                         'stars': [   'Jean Reno',
                                      'Gary Oldman',
                                      'Natalie Portman',
                                      'Danny Aiello',
                                      'Peter Appel'],
                         'title': 'The Professional',
                         'year': 1994},
    '9780767802628': {   'directors': ['Barry Sonnenfeld'],
                         'genres': [   'Comedy',
                                       'Bounty Hunters',
                                       'Alien Invasion',
                                       'Aliens',
                                       'Men in Black',
                                       'Science Fiction',
                                       'DTS',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'PG-13',
                         'stars': [   'Tommy Lee Jones',
                                      'Will Smith',
                                      'Linda Fiorentino',
                                      "Vincent D'Onofrio",
                                      'Rip Torn'],
                         'title': "Men in Black (Collector's Series)",
                         'year': 1997},
    '9780788816031': {   'directors': ['Kevin Smith'],
                         'genres': [   'Buddy Films',
                                       'Corporate Life',
                                       'Twentysomethings',
                                       'Kevin Smith',
                                       'Comedy',
                                       'DTS',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Jeff Anderson',
                                      'Lee Bendick',
                                      'Al Berkowitz',
                                      'Betsy Broussard',
                                      'Ken Clark (VII)'],
                         'title': "Clerks (Collector's Series)",
                         'year': 1994},
    '9780788826887': {   'directors': ['Joel Coen'],
                         'genres': [   'Crime',
                                       'Comic Action',
                                       'George Clooney',
                                       'Comedy',
                                       'Drama',
                                       'Buddy Films',
                                       'Obsessive Quests',
                                       'Comic Criminals',
                                       'DTS',
                                       'Action & Adventure',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'PG-13',
                         'stars': [   'Michael Badalucco',
                                      'George Clooney',
                                      'Frank Collison',
                                      'Charles Durning',
                                      'Wayne Duvall'],
                         'title': 'O Brother, Where Art Thou?',
                         'year': 2000},
    '9780788833687': {   'directors': [   'Peter Docter',
                                          'David Silverman',
                                          'Unkrich, Lee'],
                         'genres': [   'Animation',
                                       'Scary Movies & Mysteries',
                                       'Family Films',
                                       'Daring Rescues',
                                       'Computer Animation',
                                       'Feature Films',
                                       'DTS',
                                       'Animated Movies',
                                       '3-6 Years',
                                       '7-11 Years',
                                       'For the Whole Family',
                                       'Amazon.com Songs Promotion',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'G',
                         'stars': [   'Jack Angel',
                                      'Bob Bergen',
                                      'Samuel Lord Black',
                                      'Rodger Bumpass',
                                      'Steve Buscemi'],
                         'title': "Monsters, Inc. (Two-Disc Collector's Edition)",
                         'year': 2001},
    '9780788844614': {   'directors': ['Hayao Miyazaki'],
                         'genres': [   'Animation',
                                       'Heroic Missions',
                                       'Feature Films',
                                       'Studio Ghibli',
                                       'Science Fiction & Fantasy',
                                       'Fantasy Adventures',
                                       'DTS',
                                       'Japan',
                                       'Amazon.com Songs Promotion',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'PG',
                         'stars': [],
                         'title': 'Spirited Away',
                         'year': 2001},
    '9780790739250': {   'directors': ['Cameron Crowe'],
                         'genres': [   'DTS',
                                       'Comedy',
                                       'Drama',
                                       '4-for-3 Comedy',
                                       '4-for-3 Drama',
                                       '4-for-3 All DVDs',
                                       '4-for-3 DVD',
                                       'Full Screen',
                                       'Widescreen'],
                         'rating': 'PG-13',
                         'stars': [   'Matt Dillon',
                                      'Bridget Fonda',
                                      'Camilo Gallardo',
                                      'Peter Horton',
                                      'Sheila Kelley'],
                         'title': 'Singles',
                         'year': 1992},
    '9780790742243': {   'directors': ['Harold Ramis'],
                         'genres': [   'Wedding Bells',
                                       'Comic Criminals',
                                       'Harold Ramis',
                                       'Billy Crystal',
                                       'DTS',
                                       'Comedy',
                                       'DVD',
                                       'Full Screen',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Robert De Niro',
                                      'Billy Crystal',
                                      'Lisa Kudrow',
                                      'Chazz Palminteri',
                                      'Kresimir Novakovic'],
                         'title': 'Analyze This',
                         'year': 1999},
    '9780790747422': {   'directors': ['David O. Russell'],
                         'genres': [   'Comic Action',
                                       'George Clooney',
                                       'Comedy',
                                       'Drama',
                                       'Persian Gulf War',
                                       'Military Life',
                                       'Anti-War Films',
                                       'Iraq War',
                                       'DTS',
                                       'Action & Adventure',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'George Clooney',
                                      'Nora Dunn',
                                      'Ice Cube',
                                      'Holt McCallany',
                                      'Mykelti Williamson'],
                         'title': 'Three Kings',
                         'year': 1999},
    '9780790760414': {   'directors': [],
                         'genres': [   'Gift Sets',
                                       'Fawlty Towers',
                                       'DTS',
                                       'Comedy',
                                       'Television',
                                       'DVD',
                                       'Boxed Set',
                                       'Full Screen'],
                         'rating': 'NR',
                         'stars': ['Fawlty Towers'],
                         'title': 'Fawlty Towers - The Complete Series',
                         'year': 1975},
    '9780792842712': {   'directors': ['Bryan Singer'],
                         'genres': [   'Crime',
                                       'Suspense',
                                       'Neo-Noir',
                                       'DTS',
                                       'Del Toro, Benicio',
                                       'DVD',
                                       'Full Screen',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Stephen Baldwin',
                                      'Gabriel Byrne',
                                      'Benicio Del Toro',
                                      'Kevin Pollak',
                                      'Kevin Spacey'],
                         'title': 'The Usual Suspects',
                         'year': 1995},
    '9780792844891': {   'directors': ['Mel Brooks'],
                         'genres': [   'Accidental Heroes',
                                       'Unlikely Heroes',
                                       'Mel Brooks',
                                       'Comedy',
                                       'DTS',
                                       'Parody & Spoof',
                                       'DVD',
                                       'Full Screen'],
                         'rating': 'PG',
                         'stars': [   'Leslie Bevis',
                                      'JM J. Bullock',
                                      'John Candy',
                                      'Ronny Graham',
                                      'Sandy Helberg'],
                         'title': 'Spaceballs',
                         'year': 1987},
    '9780792852193': {   'directors': ['Bryan Singer'],
                         'genres': [   'Crime',
                                       'Mystery',
                                       'Neo-Noir',
                                       'DTS',
                                       'Del Toro, Benicio',
                                       'DVD',
                                       'Full Screen',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Stephen Baldwin',
                                      'Gabriel Byrne',
                                      'Benicio Del Toro',
                                      'Kevin Pollak',
                                      'Kevin Spacey'],
                         'title': 'The Usual Suspects (Special Editon)',
                         'year': 1995},
    '9780800141707': {   'directors': ['Stanley Kubrick'],
                         'genres': [   'Divers',
                                       'Military & War',
                                       'Satire',
                                       'Comedy'],
                         'rating': 'PG',
                         'stars': [   'Glenn Beck',
                                      'Frank Berry',
                                      'Jack Creley',
                                      'Hal Galili',
                                      'Sterling Hayden'],
                         'title': 'Dr. Strangelove or: How I Learned To Stop Worrying and Love the Bomb',
                         'year': 1964},
    '9786305168850': {   'directors': ['Mel Brooks'],
                         'genres': [   'Mel Brooks',
                                       'Gene Wilder',
                                       'DTS',
                                       'Special Editions',
                                       'Parody & Spoof',
                                       'Comedy',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'PG',
                         'stars': [   'Anne Beesley',
                                      'Oscar Beregi Jr.',
                                      'Rusty Blitz',
                                      'Peter Boyle',
                                      'Johnny Dennis'],
                         'title': 'Young Frankenstein (Special Edition)',
                         'year': 1974},
    '9786305508557': {   'directors': ['Mike Judge'],
                         'genres': [   'Cons & Scams',
                                       'Fighting the System',
                                       'Fish Out of Water',
                                       'Underdogs',
                                       'Corporate Life',
                                       'Black Comedy',
                                       'DTS',
                                       'DVD',
                                       'Widescreen'],
                         'rating': 'R',
                         'stars': [   'Jennifer Aniston',
                                      'Diedrich Bader',
                                      'Joe Bays',
                                      'Josh Bond',
                                      'Gary Cole'],
                         'title': 'Office Space (Widescreen Edition)',
                         'year': 1999}}

			   
